version: '3'


services:
  db:
  image: mongo:5
  restart: always
  ports:
    - 27017:27017
  environment:
    MONGODB_DATABASE: nest-archivo
  volumes:
    - ./mongo:/data/db
  # db:
  #   image: postgres:14.3
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   container_name: teslodb
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  